name: k_project_dodyversion
description: K-Project

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+1

environment:
  sdk: ">=2.2.2 "

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  #Auth stuff
  firebase_auth: ^0.11.1+6 ## import 'package:google_sign_in/google_sign_in.dart';
  google_sign_in:  ^4.0.2 ## import 'package:firebase_auth/firebase_auth.dart';

  #Firestore stuff
  cloud_firestore: ^0.12.5+1 ## import 'package:cloud_firestore/cloud_firestore.dart';
  
  #FIrebase Storage
  firebase_storage: ^3.0.0 ## import 'package:firebase_storage/firebase_storage.dart';

  #Equatable 
  equatable: ^0.2.3 ## import 'package:equatable/equatable.dart';

  #BloC
  bloc: ^0.13.0 ## import 'package:bloc/bloc.dart';
  flutter_bloc: ^0.13.0 ## import 'package:flutter_bloc/flutter_bloc.dart';

  #Validate :: to validate may user input such as Email Password etc.
  validate: ^1.7.0 ## import 'package:validate/validate.dart';

  #Localisation
  intl: 0.15.7 

  #A nicer bottom navbar
  fancy_bottom_navigation: ^0.3.2 ##import 'package:fancy_bottom_navigation/fancy_bottom_navigation.dart';
  
  #To pick image from the gallery
  image_picker: ^0.6.0+8 ##import 'package:image_picker/image_picker.dart';

  #Search page
  material_search: ^0.2.8 ##import 'package:material_search/material_search.dart';

  #carousell slider
  carousel_slider: ^1.3.0 ## https://pub.dev/packages/carousel_slider#-installing-tab-

  #UUID
  uuid: ^2.0.2 ## https://pub.dev/packages/uuid#-installing-tab-

  #Cached network image url
  cached_network_image: ^0.8.0 ##https://pub.dev/packages/cached_network_image#-installing-tab-

  #Pull to refresh
  pull_to_refresh: ^1.4.4 #https://pub.dev/packages/pull_to_refresh#-installing-tab-

    
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/placeholders/userprofile_placeholder.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
